// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkH3I8m6O1CMmZrneYc9w7TyRib-UilbI',
    appId: '1:350477443714:web:4ad3a28194d69a6edf8a9b',
    messagingSenderId: '350477443714',
    projectId: 'teste-bcd67',
    authDomain: 'teste-bcd67.firebaseapp.com',
    storageBucket: 'teste-bcd67.appspot.com',
    measurementId: 'G-LRWZLEEBC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Kt148CV_5qE9iZq_2sD1oUwwVBsCNQE',
    appId: '1:350477443714:android:cbffc37ce81f9aa3df8a9b',
    messagingSenderId: '350477443714',
    projectId: 'teste-bcd67',
    storageBucket: 'teste-bcd67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg9JWU5GwIkzbAzSq5l4ytTb_0-cxqOsY',
    appId: '1:350477443714:ios:059f7b3a624f2d2cdf8a9b',
    messagingSenderId: '350477443714',
    projectId: 'teste-bcd67',
    storageBucket: 'teste-bcd67.appspot.com',
    iosBundleId: 'com.example.aprendendo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg9JWU5GwIkzbAzSq5l4ytTb_0-cxqOsY',
    appId: '1:350477443714:ios:dace95602ee30ad1df8a9b',
    messagingSenderId: '350477443714',
    projectId: 'teste-bcd67',
    storageBucket: 'teste-bcd67.appspot.com',
    iosBundleId: 'com.example.aprendendo.RunnerTests',
  );
}
